version: "3.3"

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5433:5432"
    volumes:
      - db_coreSystem:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coreSystem
  ws:
    depends_on:
      - db
    image: danielchungara1/core-system:v1.0
    ports:
    - "8080:8080"
volumes:
  db_coreSystem: {}