version: "3.3"

services:
  api:
    image: danielchungara1/core-system:latest
    build:
      context: .
    container_name: api
    depends_on:
      - db
    ports:
    - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coreSystem?serverTimezone=America/Argentina/Buenos_Aires
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
  db:
    image: postgres:13.3-alpine
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - db_coreSystem:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coreSystem
      PGDATA: /var/lib/postgresql/data
volumes:
  db_coreSystem: {}